#include "main.h"
#include "draw.h"
#include "gba.h"

#include <stdio.h>
#include <stdlib.h>

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  TITLE,
  INIT_PLAY,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = 0x403;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    // TODO:
    // IMPL if pressing SELECT button, return to START
    switch (state) {
      case START:
        waitForVBlank();
        drawTitleScreen();
        state = TITLE; // go to title screen after startup
        break;
      case TITLE:
        // TODO: if press start -> go to PLAY
        break;
      case INIT_PLAY: // we have these init states to prevent tearing
        // TODO: Set up play screen and then go to PLAY
        break;
      case PLAY:
        /**
        TODO:
        Enemy Sprite
        Bullet Patterns and Production
        Player Sprite
        Movement of Player Sprite
        **/
        // TODO: if player collides with bullet -> go to LOSE
        // TODO: if player gets a certain score -> go to WIN
        // state = ?
        break;
      case WIN:

        break;
      case LOSE:
        // TODO: if player presses start -> retry (go back to init_play)
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
